### ISSUE TITLE
Question about datagaps

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/osteo-bior#26]
![OS1 C and N](https://github.com/Pandora-IsoMemo/osteo-bior/assets/101706974/5805addc-cda8-4545-bf7a-81792e6cef35)
[OS1 Isotopes.xlsx](https://github.com/Pandora-IsoMemo/osteo-bior/files/11546477/OS1.Isotopes.xlsx)
[OS1 Times.xlsx](https://github.com/Pandora-IsoMemo/osteo-bior/files/11546478/OS1.Times.xlsx)

Dear @arunge  
I and @isomemo were wondering what parameters are used by the model (attached) for creating interpolation between [7-7.5] and [8.5-9]. 

Time intervals are not present because a gap exists (and in the file called Times, these intervals are indeed cut).

All the best,

**Comment by arunge** [comment]
@CarloCocozza and @isomemo 

I checked your data and some old notes regarding the workaround on how to add gaps.

The time gap in your data is a missing step between the time intervals:

![image](https://github.com/Pandora-IsoMemo/osteo-bior/assets/16759098/51423fe3-bc6f-412c-9a8d-8d6eb62ddd52)

However, the way to achieve was gap is the following:

> ## Current workaround to produce a gap: 
> 1. leave out the whole line were the gap is assumed (top left 1 and bottom left 1)
> 2. rename the indivudual data after the gap (bottom left 1, 2), that is, pretend it is a second indivudual to obtain independence
> 3. copy mean/sigma data from individual 1 to obtain mean/sigma data for individual 11 (top left 2 → bottom left 3)
> 
> ![intervalGap](https://github.com/Pandora-IsoMemo/osteo-bior/assets/16759098/d19a2526-d5b9-4743-a507-1fc9e08512d2)

That is, you have point 1. done in your data, but points 2. and 3. are missing.

Additionally, there seems to be a gap between [3.5-4] and [4.5-5]. So we would have 6 individuals (e.g. 1, 11, 12, 2, 21, 22) instead of 2 individuals with respective mean/sigma values.

Does this help you?

**Comment by isomemo** [comment]
@arunge @CarloCocozza thanks for the feedback, very useful! I would like to take this step by step and my first question is related to the graph that Carlo shared. For this example, the display of a data gap is not important but we need to understand the logic behind the size of the gaps in the x-axis.

If you look at Carlo's graph there are two number gaps in the x-axis.

1) There is one between the interval [3.5-4] and the interval [4.5-5]
2) There is another one between the interval [7-7.5] and the interval [9.5-9]

Carlo had no instructions that such gaps should be shown in the x-axis. So, how did app know that there should be a gap in the x-axis and how did it know which size to set it to?


By looking at the numbers above it is a simple calculation. However, we may have applications where the intervals are not of uniform size.

**Comment by arunge** [comment]
@isomemo @CarloCocozza regarding
> Carlo had no instructions that such gaps should be shown in the x-axis. So, how did app know that there should be a gap in the x-axis and how did it know which size to set it to?

When having a time interval the model uses the mean of min and max time as time variable:
https://github.com/Pandora-IsoMemo/osteo-bior/blob/b857e236f8beefe4506c04e341ef1675306f67a6/R/estimateIntervals.R#L151-L155

Since the distance of the means of the intervals [3.5-4] and [4.5-5] (which is 1) is larger than of intervals that are next to each other like [3-3.5] and [3.5-4] (which is 0.5), the model _knows_ about the _gap_. However, when **not pretending**  that before and after a gap we have two different individuals, the estimates will be **dependent** for times before and after the gap.
When drawing the results, the mean values of the intervals are used for the x position of the points. The labels are created based on the original two time columns.

What other questions do you have?

**Comment by isomemo** [comment]
@arunge @arunge 

Ok! Now this is clearer! 

Also, if I understood correctly we can "pretend" that we have data from "multiple individuals" to produce graph gaps. That is, is it possible to show in the same output graphs from multiple individuals using the same graph colour. Correct?

**Comment by arunge** [comment]
As discussed, I will add optional (with a checkbox) new labels at each of the ends of the x axis as described [here](https://github.com/Pandora-IsoMemo/osteo-bior/issues/26#issuecomment-1568714893).

**Comment by arunge** [comment]
@isomemo With [version 23.09.1](https://github.com/Pandora-IsoMemo/osteo-bior/pull/29) the option to extend x-axis labels is online on [OsteoBioR beta](https://isomemoapp.com/app/osteo-bio-r-beta). All what we discussed is done here.

![image](https://github.com/Pandora-IsoMemo/osteo-bior/assets/16759098/ec66070e-b87a-4bc6-b7b2-0915baf81b24)

Please note, that it is still necessary to add gaps inbetween data points manually by splitting individuals as described in the [post above](https://github.com/Pandora-IsoMemo/osteo-bior/issues/26#issuecomment-1562916151).
