### ISSUE TITLE
Cannot use alphanumeric Individual IDs in batch option

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/osteo-bior#35]
When I want to model different individuals in a batch (as in the attached files), I cannot use their original codes or individual IDs. In fact, when trying to upload these files in OsteoBioR, I receive the following error: "Please provide a dataset with all numeric variables.". If I tick on the option "First column contains rownames", this error does not appear and I can proceed. However, the different individuals will not appear as variable when trying to model. 

I know that the solution is that of giving just sequential numeric codes to each individual. But it would be better, especially for large numbers, to use the original code or ID as reference.

@arunge 

[Isotopes.xlsx](https://github.com/Pandora-IsoMemo/osteo-bior/files/13539303/Isotopes.xlsx)
[Renewal rates.xlsx](https://github.com/Pandora-IsoMemo/osteo-bior/files/13539304/Renewal.rates.xlsx)

**Comment by arunge** [comment]
@CarloCocozza I checked the code. During upload there is a check if all colums are numeric, however, the code does not require that the column containing the ids is numeric. I am now excluding the **first** column from the check, please use the **first** column for the `ids`, and do **NOT** check "First column contains rownames". This would set names for each row and remove the first column from the data.
With version 23.12.2.2 on [OsteoBior beta](https://isomemoapp.com/app/osteo-bio-r-beta) this change is now online.

Could you test your data again? Please, feel free to re-open the issue if you still have issues with the ids.

**Comment by CarloCocozza** [comment]
Hi @arunge 

I tested it again with the same files. Even though I can now set up the model, the server crashes and the page greys out when I click on fit the model. I used the version you linked and I used default options.

**Comment by arunge** [comment]
@CarloCocozza With [version 24.01.1](https://github.com/Pandora-IsoMemo/osteo-bior/pull/42) on [OsteoBior beta](https://isomemoapp.com/app/osteo-bio-r-beta) it is now possible to 
- provide non-numeric rownames, and
- to use the rownames as individual variable

However, all other variables must be numeric, otherwise data will not be accepted.

I tested the data that you provided from [above](https://github.com/Pandora-IsoMemo/osteo-bior/issues/35#issue-2022564733). The app reacted very slow after loading the renewal rates, model calculation took a long time, and afterwards navigating between tabs was very slow. Possibly the number of columns is too large.
Please check your model and model results carefully and make sure that model assumption are satisfied!

![2024-01-29_18-49_rownamesAsIndVar](https://github.com/Pandora-IsoMemo/osteo-bior/assets/16759098/b5f337d9-329c-4f36-b52d-93ed02b1777e)
