### ISSUE TITLE
Cannot download model with Beta Version

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/osteo-bior#36]
[METi_239 Isotopes.xlsx](https://github.com/Pandora-IsoMemo/osteo-bior/files/13548522/METi_239.Isotopes.xlsx)
[METi_239 Renewal Rates.xlsx](https://github.com/Pandora-IsoMemo/osteo-bior/files/13548524/METi_239.Renewal.Rates.xlsx)

For the attached files, in the beta online version, the model cannot be saved after being run. 

I attach a screenshot of the error:
![Cannot download model OsteoBioR](https://github.com/Pandora-IsoMemo/osteo-bior/assets/101706974/cf479e78-8a30-40f7-a116-660fe80d0a5f)

I have used 5000 Iterations, 1000 Burnin and 4 MCMC. 

@arunge

**Comment by arunge** [comment]
@CarloCocozza There was a bug in version 23.10.0 with the model down- and upload, that I fixed with version 23.10.1: https://github.com/Pandora-IsoMemo/osteo-bior/commit/b2e608bf3d8bc5737a61ea21c2da34071084de60

So, download is working again for the remote test model. However, I am not sure if this fixes your issue. I can let your model run in later in the evening and test if a download is possible now.
